version: '3'
services:
    yude-vs-robot:
        restart: always
        container_name: yude-vs-robot
        image: yude/yude-vs-robot:latest
        volumes:
          - "./data:/app/data"
        environment:
          # Twitter API related
          - CK=
          - CS=
          - AT=
          - AS=