version: '3'
services:
    app:
        restart: always
        container_name: yude-vs-robot
        build: .
        volumes:
          - "./data:/app/data"
        environment:
          # Twitter API related
          - CK=
          - CS=
          - AT=
          - AS=